### ISSUE TITLE
btoa package breaks upgrade from 2.7.9 to 2.8 in webpack

### ISSUE THREAD

**Issue by smalesys** [igvteam/igv.js#1325]
Hello,

I have an issue with the upgrade from 2.7.9 to 2.8 and webpack 4. Upgrading to 2.8 or higher make breaks the build with the error:
```
ERROR in ./node_modules/igv/dist/igv.js
Module not found: Error: Can't resolve 'btoa'
```
When comparing the build of the 2.7.9 and 2.8.1 versions, it seems that there were some changes made in the code concerning the btoa package, but i can't figure the exact origin, nor if i can fix it by changing my webpack config.

Thanks in advance for your time !

**Comment by jrobinso** [comment]
We don't use webpack but I did find an inadvertent run-time dependency on btoa in the "igv-utils" package.  It is only used for unit tests, which are run in node, and should not be needed for the browser runtime.   I have removed it and pushed the fix as release 2.8.2.   Again we don't use webpack so I couldn't verify it but it should fix the problem.

**Comment by smalesys** [comment]
Thank you for the update, i think [this change](https://github.com/igvteam/igv-utils/compare/v1.2.6...v1.2.7#diff-67a66d59ceb6ebd18c59e4d7db242fe21a16b2ec391851d5398e245401e5f9f1) indeed partially fix the issue, since the problem is with the import of the btoa package.

There is still an error, this time with igv-ui i think. To be as accurate i can, when i look in the igv.js build of my node module, this part requiring the btoa package on line **22416** is generating the error: 

```js
      output[pos++] = adler >> 24 & 0xff;
      output[pos++] = adler >> 16 & 0xff;
      output[pos++] = adler >> 8 & 0xff;
      output[pos++] = adler & 0xff;
      return output;
    };

    if (typeof btoa === 'undefined') {
      require('btoa');
    }

    if (typeof process === 'object' && typeof window === 'undefined') {
      global.atob = function (str) {
        return Buffer.from(str, 'base64').toString('binary');
      };
    }
```

Which apparently corresponds to [this btoa require](https://github.com/igvteam/igv-ui/blob/ecb455c48cf46e8d36bfa3c868c2d1df59fa0d11/dist/igv-ui.js#L5533) of the igv-ui build. Which is strange because it doesn't seem to be used anywhere else in the igv-ui package and btoa is not part of the dependencies either.

Thanks again for your time.

**Comment by jrobinso** [comment]
Ah yes, igv-ui uses igv-utils.   Sorry I missed that one.   Webpack must be very aggressive about finding "require".

**Comment by jrobinso** [comment]
@smalesys OK let's try again, 2.8.3

**Comment by smalesys** [comment]
Build complete, and everything seems to be working fine.

Thank you very much !
