### ISSUE TITLE
Missing chromosomes from chr10 to chr22 in cnvpytor track

### ISSUE THREAD

**Issue by beskns** [igvteam/igv.js#1788]
# The program does not show chromosomes from chr10 to chr22 in cnvpytor track at any zoom level

(Tested on versions 2.15.5 and 2.15.11)

## IGV image:
![Screenshot from 2024-03-29 11-11-07](https://github.com/igvteam/igv.js/assets/36955333/5fd91d7d-21ff-4db6-afd0-9164ac4256d9)
## cnvpytor plot:
![pytor global 0000](https://github.com/igvteam/igv.js/assets/36955333/a50948c3-5b66-4cb0-a4ef-c68020db5f02)

## cnvpytor file:
https://disk.yandex.ru/d/yjnsXE7iXjZfCw

**Comment by jrobinso** [comment]
Thanks for the test data.  I found the problem, the hdf5 reader expects strings to be null-terminated (i.e. end with \0).   The chromosome names in the range chr10 -> chr22 are not null terminated.   I don't know if this is a dataset bug, or a hdf5 reader bug, but I think I can fix it.  @arpanda have you seen this issue before?  It will probably happen with any file created with the pipeline or program that @beskns has used.

**Comment by arpanda** [comment]
Hi Jim,
For the first time, I am seeing this issue. The HDF5 reader seems to be malfunctioning when attempting to read the 'rd_chromosomes' dataset, resulting in empty entries for chromosomes chr10 -> chr22.
```
['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', '', '', '', '', '', '', '', '', '', '', '', '', '', 'chrX', 'chrY', 'chrM']
```
However, when employing CNVpytor (a Python-based tool) to access the data, this issue does not occur. This suggests a potential bug within the HDF5 reader.

Looks like you already tried to fix that bug in the hdf5 reader.

**Comment by jrobinso** [comment]
Yes I fixed it.   The reader expects null terminated strings, the chromosome names with 5 characters are not null terminated, to null terminate those strings would require a data size of 6.    I do think variable length strings should always be null terminated, but I have changed the reader to accept a mix of null terminated and fixed length strings so it should work now.

If this is the first time you've seen this either other datasets did null terminate all strings,  or you did not have chromosome names == the declared length of the strings (5 in this dataset).     I don't know how you are creating these hdf5 files,  some genomes of course have chromosome names that are much longer than 5 characters.

**Comment by arpanda** [comment]
The 'rd_chromosomes', its in variable length string format. For the example pytor file, the rd_chromsome's dtype is 'S24' here its `S5`. The python library auto assigns the terminal character. 

It appears that no space is allocated for the null character, especially considering it's already a 5-character string, such as 'chr10'. However, it's worth exploring whether the full string length serves as the string terminal for the HDF5 file or not. I will investigate about it.

**Comment by jrobinso** [comment]
Actually the datatype is "H5T_STR_NULLPAD",  which is a fixed length string with null padding.   With the change to the jsfive fork used by the reader this should now work.   I don't think we need to change anything else.

**Comment by beskns** [comment]
It works :) Thank you very much!

**Comment by jrobinso** [comment]
Great, the error was mine, I misinterpreted a fixed length null padded string for a null terminated string.

**Comment by beskns** [comment]
Hi Jim! 
For some reason this error persisted in the new release (2.15.12). Please look again.

**Comment by jrobinso** [comment]
It looks like that patch didn't get released in the 2.15.X branch.   I will update that branch and do a new release, 2.15.13,  should be done within the hour.

**Comment by jrobinso** [comment]
@beskns OK 2.15.13 is released, give that a try.

**Comment by jrobinso** [comment]
@beskns Hang on, npmjs does not appear to be updated.   Not sure what's going on.   In any event 2.15.13 has the fix and should appear soon.
