### ISSUE TITLE
TDF file support

### ISSUE THREAD

**Issue by gaitat** [igvteam/igv.js#383]
Hi,

I have seen the issues discussing about TDF support and I got the impression that release 1.0.8 would contain the support. Playing with the code though, it seems that TDF file support will be post 1.0.8. Is this correct?

Also playing with the master branch (which I know is not released yet) I noticed that our current samples do not work as they used to. Am I correct to assume that there is some API change between release 1.0.8 and master branch? 

Thank you

**Comment by jrobinso** [comment]
To be honest I didn't realize TDF was not in the 1.0x branch.    The master branch will be released as 1.1 by the end of August.     It should be backward compatible with 1.0.8,  the API is extended but not changed.    Could you open another issue, preferably with sample files or steps to reproduce,  re the problem you are having?

I will look into merging TDF support into 1.0.x,  but we should fix the issues you are having with the master branch.

**Comment by jrobinso** [comment]
I've merged the TDF support to branch 1.0.2.  The branch is poorly named,  it should be 1.0.x,  all 1.0.x releases are from this branch.   I can release this as 1.0.9,  but could you pull and confirm that it works for you?

Also, we should find and fix your problem with the master branch.

**Comment by gaitat** [comment]
Wanted to let you know that 1.0.2 worked for me while testing TDF file support. Am I correct to assume that only single track TDF files are supported? That is what I read in some other issue and just wanted to verify. 

As for the master, re-tested again, still does not work with no errors (either console or popups) I would need to spend more time to figure out why.

**Comment by jrobinso** [comment]
Yes, only single-track TDFs are supported at this time.

If you can create a reproducible test case we can run and open a git issue
I will look at the problem in master.   You can continue forever with 1.0.9
support but after we release 1.1 from master it will be an
unsupported version.

**Comment by gaitat** [comment]
What is the difference between 1.1.0 and 1.0.9? Does 1.0.9 contain the TDF file support that the branch 1.0.2 has? 

I will try to test master with public samples. Currently I am testing with private samples.

**Comment by jrobinso** [comment]
The 1.0.2 branch is poorly named, it should be "1.0.x".   1.0.9 is a tag on
the release taken from the 1.0.2 branch.   In other words 1.0.9 is at the
tip of the 1.0.2 branch.  Sorry for this confusion.
